before_script:
    - angr-test sync hard

### local
simuvex:
    script: "angr-test simuvex"
    tags: [angr]

lint:
    script: "angr-test lint"
    tags: [angr]

### first level
angr:
    script: "angr-test angr"
    tags: [angr]

fidget:
    script: "angr-test fidget"
    tags: [angr]

angrop:
    script: "angr-test angrop"
    tags: [angr]

topsecret:
    script: "angr-test top-secret"
    tags: [angr]

driller:
    script: "angr-test driller"
    tags: [angr]

tracer:
    script: "angr-test tracer"
    tags: [angr]

rex:
    script: "angr-test rex"
    tags: [angr]

# FIXME: disable until tests are fixed
# pwnrex:
#     script: "angr-test pwnrex"
#     tags: [angr]

docs:
    script: "angr-test docs"
    tags: [angr]
